### PR TITLE
update compute_readable_h5.py

### PR DESCRIPTION
**Pull request by keiyamamo**
This is a re-implementation of existing [compute_readable_h5.py](https://github.com/KVSlab/Aneurysm_Workflow_FSI/blob/master/postprocessing_fenics/compute_readable_h5.py)

The purpose of this script is the same as before, creating HDF5 file that can be read with FEniCS for other post-processing purposes such as stress, strain, and hemodynamics computation. 

There is a high chance that these newly added scripts will be updated as we work more on other FEniCS related script, but this script itself is usable based on preliminary test of computing WSS and solid stresses DAB’s script.

### CODE REVIEW

**Review by johannesring — COMMENTED** [review]
Looks fine. I have a few comments in addition to the minor inline comments:
* When running the script with default arguments on a simulation with five cycles, the script does not stop at `0.951`, which is set as the default end time. Removing the `try`-`except` in the `while`-loop and adding a `else` clause with a `break` as suggested, fixes this problem.
* Should the default end time be perhaps the end time for the simulation instead of `0.951`?
* There is a mix of using `logging` and `print` statements. Maybe use `logging` throughout the script?

**Comment by keiyamamo** [comment]
Hi @johannesring  Thank you so much for the comments and suggestions! I incorporated most of the suggestions. Regarding the while loop, I agree that the current while loop needs some more work to make it robust. I will work on that tomorrow and will let you know when it is ready for review again.

**Comment by keiyamamo** [comment]
Hi @johannesring 
It is ready for a review again! Please let me know if you have suggestions.

**Review by johannesring — APPROVED** [review]
Looks good now and works well. Thanks!

**Pull request merged**
